#!/bin/bash
# Runs one nz-microsite-loop iteration every 20 minutes via launchd.
# Spawns a non-interactive codex session that follows the loop skill, then
# logs the outcome.
#
# Robustness contract (learned from real failures):
# - The lock records the PID; a lock whose PID is dead or older than
#   LOCK_MAX_MINUTES is stale and gets cleared, so a crashed run never
#   blocks the loop forever.
# - A lock skip means an iteration or heal is already running, so it never
#   spawns another heal: a live lock is active work, not a blocker.
# - Each agent run is capped at RUN_TIMEOUT_MINUTES and killed if it stalls,
#   then retried on the next tick.
# - Each iteration prunes merged feat/microsite-loop-* worktrees, branches,
#   and stale agents first, so a stalled run cannot pile up artifacts for
#   the next one to collide with.
set -euo pipefail

# launchd runs with a minimal PATH; node lives under mise, so add it or the
# codex binary (a node script) cannot start.
export PATH="$HOME/.local/share/mise/installs/node/lts/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# The codex model provider needs this key; launchd does not inherit the
# interactive shell environment, so load it from a 0600 file if present.
ENV_FILE="$HOME/.config/nz-microsite-loop.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
else
  echo "$(date '+%F %T') warning: $ENV_FILE missing; agent runs may fail auth" >> "$LOG"
fi

REPO="$HOME/code/nz-data-lab"
PROMPT="$REPO/scripts/loop-prompt.txt"
HEAL_PROMPT="$REPO/scripts/heal-loop-prompt.txt"
LOG="$HOME/Library/Logs/nz-microsite-loop.log"
STATE="$HOME/Library/Logs/nz-microsite-loop-state.json"
LOCK="$HOME/Library/Logs/nz-microsite-loop.lock"
CODEX_BIN="$HOME/.local/share/mise/installs/node/lts/bin/codex"
MAX_CONSECUTIVE_SKIPS=3
LOCK_MAX_MINUTES=45
RUN_TIME_MAX_MINUTES=40

mkdir -p "$(dirname "$LOG")"

log() {
  echo "$(date '+%F %T') $*" >> "$LOG"
}

skip() {
  local reason="$1"
  log "skipped: $reason"
  python3 - "$reason" <<'PY'
import json, os, sys
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
state = {}
if os.path.exists(path):
    try:
        state = json.load(open(path))
    except Exception:
        state = {}
state['consecutiveSkips'] = state.get('consecutiveSkips', 0) + 1
state['lastSkipReason'] = sys.argv[1]
state['lastSkipAt'] = __import__('datetime').datetime.now().isoformat()
json.dump(state, open(path, 'w'), indent=2)
PY
}

reset_state() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
json.dump({'consecutiveSkips': 0, 'lastSkipReason': None, 'lastSkipAt': None}, open(path, 'w'), indent=2)
PY
}

consecutive_skips() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
try:
    state = json.load(open(path))
    print(state.get('consecutiveSkips', 0))
except Exception:
    print(0)
PY
}

maybe_heal() {
  if [ "$(consecutive_skips)" -ge "$MAX_CONSECUTIVE_SKIPS" ]; then
    log "healing: spawning fix session for repeated blocker"
    "$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$HEAL_PROMPT")" >> "$LOG" 2>&1 || true
    reset_state
  fi
}

# Acquire the lock, clearing a stale one first.
acquire_lock() {
  # Legacy lock from the mkdir-based wrapper: a directory, not a file.
  if [ -d "$LOCK" ]; then
    log "clearing legacy directory lock"
    rmdir "$LOCK" 2>/dev/null || true
  fi
  if [ -f "$LOCK" ]; then
    local pid age
    pid=$(cat "$LOCK" 2>/dev/null || echo '')
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      age=$(( $(date +%s) - $(stat -f %m "$LOCK" 2>/dev/null || echo 0) ))
      if [ "$age" -lt "$((LOCK_MAX_MINUTES * 60))" ]; then
        log "skipped: previous iteration still running (pid $pid)"
        skip "previous iteration still running"
        return 1
      fi
      log "clearing stale lock: pid $pid alive but lock older than ${LOCK_MAX_MINUTES}m"
      rm -f "$LOCK"
    else
      log "clearing stale lock: pid $pid not running"
      rm -f "$LOCK"
    fi
  fi
  echo "$$" > "$LOCK"
  return 0
}

if ! acquire_lock; then
  exit 0
fi
trap 'rm -f "$LOCK"' EXIT

log "===== loop iteration start ====="

# Prune the loop's own merged worktrees, branches, and stale agents from
# earlier iterations before anything else, so even a run that then stalls
# leaves nothing for the next one to collide with.
"$REPO/scripts/prune-loop-artifacts.sh" >> "$LOG" 2>&1 || log "prune reported a problem (non-fatal)"

# The loop merges to main and pushes; only run from a clean main.
# next-env.d.ts is regenerated by every build, so it never blocks a run.
# The quality loop appends its daily notes to LOOP-NOTES.md but does not
# always commit them before its iteration ends, so an uncommitted notes
# entry must not block this loop either. This loop never writes that file,
# and git still refuses any merge that would overwrite a dirty file, so the
# safety net stays intact.
# The quality loop commits to main concurrently, so give a dirty main a
# short window to clear before counting it as a skip.
cd "$REPO"
DIRTY_RETRY_MINUTES=5
DIRTY_EXCLUDES=(
  ':(exclude)apps/web/next-env.d.ts'
  ':(exclude)skills/quality-issue-loop/LOOP-NOTES.md'
)
dirty_waited=0
while ! git diff --quiet -- . "${DIRTY_EXCLUDES[@]}"; do
  if [ "$dirty_waited" -ge "$((DIRTY_RETRY_MINUTES * 60))" ]; then
    log "main still dirty after ${DIRTY_RETRY_MINUTES}min; files: $(git diff --name-only | tr '\n' ' ')"
    skip "main has uncommitted changes"
    maybe_heal
    exit 0
  fi
  log "main is dirty (concurrent lane working); retrying in 30s"
  sleep 30
  dirty_waited=$((dirty_waited + 30))
done
if [ "$(git branch --show-current)" != "main" ]; then
  skip "not on main"
  exit 0
fi
git fetch origin main --quiet || true
if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
  skip "main is behind origin/main (pull first)"
  maybe_heal
  exit 0
fi

# Spawn the agent with a hard time cap so a stuck session can't hold the
# lock forever. Headless: approval never, full access (mirrors config.toml).
"$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$PROMPT")" >> "$LOG" 2>&1 &
agent_pid=$!

waited=0
killed=0
while kill -0 "$agent_pid" 2>/dev/null; do
  sleep 30
  waited=$((waited + 30))
  if [ "$waited" -ge "$((RUN_TIME_MAX_MINUTES * 60))" ]; then
    # kill -0 reports success on a zombie too, so only count a real stall:
    # a zombie (or vanished) process means the agent already exited and wait
    # will report its true status below.
    stat=$(ps -o stat= -p "$agent_pid" 2>/dev/null || true)
    case "$stat" in
      ""|Z*) break ;;
    esac
    log "killing stalled agent after ${RUN_TIME_MAX_MINUTES}min"
    # Preserve any in-progress work in the loop's worktrees before the kill,
    # so a stall never strands uncommitted changes. Junk *.full backups from
    # the apply_patch workaround are excluded from the WIP commit.
    while IFS=$'\t' read -r wt_path; do
      if [ -n "$(git -C "$wt_path" status --porcelain 2>/dev/null)" ]; then
        git -C "$wt_path" add -A -- . ':(exclude)*.full' 2>/dev/null || true
        # --no-verify: a stalled agent can leave mid-edit files that fail
        # lint; the WIP snapshot is preservation, not a quality gate.
        git -C "$wt_path" commit -q --no-verify -m "wip: preserve stalled loop work" 2>/dev/null || true
        log "preserved stalled work in $wt_path"
      fi
    done < <(git worktree list --porcelain | awk '/^worktree /{print $2}' | grep 'feat/microsite-loop-')
    kill "$agent_pid" 2>/dev/null || true
    killed=1
    break
  fi
done

if wait "$agent_pid"; then
  status=0
else
  status=$?
fi

if [ "$killed" -eq 1 ]; then
  log "loop iteration STALLED: agent killed at the ${RUN_TIME_MAX_MINUTES}min cap"
  skip "agent stalled at the time cap"
  maybe_heal
  exit 1
fi

if [ "$status" -eq 0 ]; then
  log "loop iteration finished ok"
  reset_state
  exit 0
fi

log "loop iteration FAILED (exit $status)"
exit "$status"
