#!/bin/bash
# Runs one nz-microsite-loop iteration every 20 minutes via launchd.
# Spawns a non-interactive codex session that follows the loop skill, then
# logs the outcome. Guarded by a lockfile so iterations never overlap.
#
# Self-healing: if the loop is skipped too many times in a row, this wrapper
# spawns a "heal the loop" session that diagnoses and fixes the blocker, so
# the loop can improve itself even when it cannot ship.
set -euo pipefail

REPO="$HOME/code/nz-data-lab"
PROMPT="$REPO/scripts/loop-prompt.txt"
HEAL_PROMPT="$REPO/scripts/heal-loop-prompt.txt"
LOG="$HOME/Library/Logs/nz-microsite-loop.log"
STATE="$HOME/Library/Logs/nz-microsite-loop-state.json"
LOCK="$HOME/Library/Logs/nz-microsite-loop.lock"
CODEX_BIN="$HOME/.local/share/mise/installs/node/lts/bin/codex"
MAX_CONSECUTIVE_SKIPS=3

mkdir -p "$(dirname "$LOG")"

# Never overlap: if a previous iteration is still running, skip this tick.
if ! mkdir "$LOCK" 2>/dev/null; then
  echo "$(date '+%F %T') skipped: previous iteration still running" >> "$LOG"
  exit 0
fi
trap 'rmdir "$LOCK" 2>/dev/null || true' EXIT

log_skip() {
  local reason="$1"
  echo "$(date '+%F %T') skipped: $reason" >> "$LOG"
  python3 - "$reason" <<'PY'
import json, os, sys
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
state = {}
if os.path.exists(path):
    try:
        state = json.load(open(path))
    except Exception:
        state = {}
state['consecutiveSkips'] = state.get('consecutiveSkips', 0) + 1
state['lastSkipReason'] = sys.argv[1]
state['lastSkipAt'] = __import__('datetime').datetime.now().isoformat()
json.dump(state, open(path, 'w'), indent=2)
PY
}

reset_state() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
json.dump({'consecutiveSkips': 0, 'lastSkipReason': None, 'lastSkipAt': None}, open(path, 'w'), indent=2)
PY
}

consecutive_skips() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
try:
    state = json.load(open(path))
    print(state.get('consecutiveSkips', 0))
except Exception:
    print(0)
PY
}

echo "$(date '+%F %T') ===== loop iteration start =====" >> "$LOG"

# The loop merges to main and pushes; only run from a clean main.
# next-env.d.ts is regenerated by every build, so it never blocks a run.
cd "$REPO"
if ! git diff --quiet -- . ':(exclude)apps/web/next-env.d.ts'; then
  log_skip "main has uncommitted changes"
  if [ "$(consecutive_skips)" -ge "$MAX_CONSECUTIVE_SKIPS" ]; then
    echo "$(date '+%F %T') healing: spawning fix session for repeated blocker" >> "$LOG"
    "$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$HEAL_PROMPT")" >> "$LOG" 2>&1 || true
    reset_state
  fi
  exit 0
fi
if [ "$(git branch --show-current)" != "main" ]; then
  log_skip "not on main"
  exit 0
fi
git fetch origin main --quiet || true
if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
  log_skip "main is behind origin/main (pull first)"
  if [ "$(consecutive_skips)" -ge "$MAX_CONSECUTIVE_SKIPS" ]; then
    echo "$(date '+%F %T') healing: spawning fix session for repeated blocker" >> "$LOG"
    "$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$HEAL_PROMPT")" >> "$LOG" 2>&1 || true
    reset_state
  fi
  exit 0
fi

# Spawn the agent. Headless: approval never, full access (mirrors config.toml).
if "$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$PROMPT")" >> "$LOG" 2>&1; then
  echo "$(date '+%F %T') loop iteration finished ok" >> "$LOG"
  reset_state
else
  status=$?
  echo "$(date '+%F %T') loop iteration FAILED (exit $status)" >> "$LOG"
  exit "$status"
fi
