#!/bin/bash
# Runs one nz-microsite-loop iteration every 20 minutes via launchd.
# Spawns a non-interactive codex session that follows the loop skill, then
# logs the outcome.
#
# Robustness contract (learned from real failures):
# - The lock records the PID; a lock whose PID is dead or older than
#   LOCK_MAX_MINUTES is stale and gets cleared, so a crashed run never
#   blocks the loop forever.
# - Lock skips and stale-lock clears count toward the heal counter, so a
#   persistently blocked loop spawns a self-healing session.
# - Each agent run is capped at RUN_TIMEOUT_MINUTES and killed if it stalls,
#   then retried on the next tick.
set -euo pipefail

# launchd runs with a minimal PATH; node lives under mise, so add it or the
# codex binary (a node script) cannot start.
export PATH="$HOME/.local/share/mise/installs/node/lts/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# The codex model provider needs this key; launchd does not inherit the
# interactive shell environment, so load it from a 0600 file if present.
ENV_FILE="$HOME/.config/nz-microsite-loop.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
else
  echo "$(date '+%F %T') warning: $ENV_FILE missing; agent runs may fail auth" >> "$LOG"
fi

REPO="$HOME/code/nz-data-lab"
PROMPT="$REPO/scripts/loop-prompt.txt"
HEAL_PROMPT="$REPO/scripts/heal-loop-prompt.txt"
LOG="$HOME/Library/Logs/nz-microsite-loop.log"
STATE="$HOME/Library/Logs/nz-microsite-loop-state.json"
LOCK="$HOME/Library/Logs/nz-microsite-loop.lock"
CODEX_BIN="$HOME/.local/share/mise/installs/node/lts/bin/codex"
MAX_CONSECUTIVE_SKIPS=3
LOCK_MAX_MINUTES=45
RUN_TIME_MAX_MINUTES=40

mkdir -p "$(dirname "$LOG")"

log() {
  echo "$(date '+%F %T') $*" >> "$LOG"
}

skip() {
  local reason="$1"
  log "skipped: $reason"
  python3 - "$reason" <<'PY'
import json, os, sys
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
state = {}
if os.path.exists(path):
    try:
        state = json.load(open(path))
    except Exception:
        state = {}
state['consecutiveSkips'] = state.get('consecutiveSkips', 0) + 1
state['lastSkipReason'] = sys.argv[1]
state['lastSkipAt'] = __import__('datetime').datetime.now().isoformat()
json.dump(state, open(path, 'w'), indent=2)
PY
}

reset_state() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
json.dump({'consecutiveSkips': 0, 'lastSkipReason': None, 'lastSkipAt': None}, open(path, 'w'), indent=2)
PY
}

consecutive_skips() {
  python3 - <<'PY'
import json, os
path = os.path.expanduser('~/Library/Logs/nz-microsite-loop-state.json')
try:
    state = json.load(open(path))
    print(state.get('consecutiveSkips', 0))
except Exception:
    print(0)
PY
}

maybe_heal() {
  if [ "$(consecutive_skips)" -ge "$MAX_CONSECUTIVE_SKIPS" ]; then
    log "healing: spawning fix session for repeated blocker"
    "$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$HEAL_PROMPT")" >> "$LOG" 2>&1 || true
    reset_state
  fi
}

# Acquire the lock, clearing a stale one first.
acquire_lock() {
  # Legacy lock from the mkdir-based wrapper: a directory, not a file.
  if [ -d "$LOCK" ]; then
    log "clearing legacy directory lock"
    rmdir "$LOCK" 2>/dev/null || true
  fi
  if [ -f "$LOCK" ]; then
    local pid age
    pid=$(cat "$LOCK" 2>/dev/null || echo '')
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      age=$(( $(date +%s) - $(stat -f %m "$LOCK" 2>/dev/null || echo 0) ))
      if [ "$age" -lt "$((LOCK_MAX_MINUTES * 60))" ]; then
        log "skipped: previous iteration still running (pid $pid)"
        skip "previous iteration still running"
        return 1
      fi
      log "clearing stale lock: pid $pid alive but lock older than ${LOCK_MAX_MINUTES}m"
      rm -f "$LOCK"
    else
      log "clearing stale lock: pid $pid not running"
      rm -f "$LOCK"
    fi
  fi
  echo "$$" > "$LOCK"
  return 0
}

if ! acquire_lock; then
  maybe_heal
  exit 0
fi
trap 'rm -f "$LOCK"' EXIT

log "===== loop iteration start ====="

# The loop merges to main and pushes; only run from a clean main.
# next-env.d.ts is regenerated by every build, so it never blocks a run.
cd "$REPO"
if ! git diff --quiet -- . ':(exclude)apps/web/next-env.d.ts'; then
  skip "main has uncommitted changes"
  maybe_heal
  exit 0
fi
if [ "$(git branch --show-current)" != "main" ]; then
  skip "not on main"
  exit 0
fi
git fetch origin main --quiet || true
if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
  skip "main is behind origin/main (pull first)"
  maybe_heal
  exit 0
fi

# Spawn the agent with a hard time cap so a stuck session can't hold the
# lock forever. Headless: approval never, full access (mirrors config.toml).
"$CODEX_BIN" exec --cd "$REPO" -c 'approval_policy="never"' -c 'sandbox_mode="danger-full-access"' "$(cat "$PROMPT")" >> "$LOG" 2>&1 &
agent_pid=$!

waited=0
while kill -0 "$agent_pid" 2>/dev/null; do
  sleep 30
  waited=$((waited + 30))
  if [ "$waited" -ge "$((RUN_TIME_MAX_MINUTES * 60))" ]; then
    log "killing stalled agent after ${RUN_TIME_MAX_MINUTES}min"
    kill "$agent_pid" 2>/dev/null || true
    break
  fi
done

if wait "$agent_pid"; then
  log "loop iteration finished ok"
  reset_state
else
  status=$?
  log "loop iteration FAILED (exit $status)"
  exit "$status"
fi
